from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import structlog
from jinja2 import Template

from qe_platform.config import Settings
from qe_platform.models.report import (
    CoverageMetric,
    PipelineReport,
    SelfHealingMetric,
    TestExecutionResult,
    TestStatus,
    TokenCostMetric,
)
from qe_platform.models.test_case import TestGenerationRun

logger = structlog.get_logger()

MARKDOWN_TEMPLATE = """\
# QE Platform - Test Generation Report

**Run ID:** {{ report.run_id }}
**Spec:** {{ report.spec_title }}
**Generated:** {{ report.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC') }}
**Duration:** {{ "%.2f"|format(report.duration_seconds) }}s

---

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | {{ report.total_tests }} |
| Passed | {{ report.passed }} |
| Failed | {{ report.failed }} |
| Errors | {{ report.error }} |
| Healed | {{ report.healed }} |
| Pass Rate | {{ "%.1f"|format(report.pass_rate) }}% |

## Coverage

| Metric | Value |
|--------|-------|
| Endpoints Covered | {{ report.coverage.covered_endpoints }}/{{ report.coverage.total_endpoints }} |
| Coverage | {{ "%.1f"|format(report.coverage.coverage_pct) }}% |

### Test Type Distribution
{% for test_type, count in report.coverage.test_type_distribution.items() %}
- **{{ test_type }}**: {{ count }}
{% endfor %}

### Risk Tier Distribution
{% for tier, count in report.coverage.risk_tier_distribution.items() %}
- **{{ tier }}**: {{ count }}
{% endfor %}

## Self-Healing

| Metric | Value |
|--------|-------|
| Failures Detected | {{ report.self_healing.total_failures }} |
| Heal Attempts | {{ report.self_healing.heal_attempts }} |
| Successful Heals | {{ report.self_healing.heal_successes }} |
| Heal Rate | {{ "%.1f"|format(report.self_healing.heal_rate) }}% |

## Token Usage

| Metric | Value |
|--------|-------|
| Total Tokens | {{ report.token_cost.total_tokens }} |
| Total Cost | ${{ "%.4f"|format(report.token_cost.total_cost_usd) }} |
| Avg Cost/Test | ${{ "%.6f"|format(report.token_cost.avg_cost_per_test) }} |

## Failed Tests
{% if failed_tests %}
{% for test in failed_tests %}
### {{ test.test_name }}
- **Status:** {{ test.status.value }}
- **Error:** {{ test.error_message }}
- **Duration:** {{ "%.2f"|format(test.duration_ms) }}ms
{% if test.healed %}- **Healed:** {{ test.original_locator }} → {{ test.healed_locator }}{% endif %}

{% endfor %}
{% else %}
No failed tests.
{% endif %}

---
*Generated by QE Intelligent Test Generation Platform*
"""


class ReportGenerator:
    def __init__(self, settings: Settings | None = None) -> None:
        self._settings = settings or Settings()

    def generate(
        self,
        run: TestGenerationRun,
        results: list[TestExecutionResult],
        token_cost: TokenCostMetric | None = None,
        self_healing: SelfHealingMetric | None = None,
        duration_seconds: float = 0.0,
    ) -> PipelineReport:
        passed = sum(1 for r in results if r.status == TestStatus.PASSED)
        failed = sum(1 for r in results if r.status == TestStatus.FAILED)
        errors = sum(1 for r in results if r.status == TestStatus.ERROR)
        healed = sum(1 for r in results if r.healed)
        total = len(results)

        test_type_dist: dict[str, int] = {}
        risk_tier_dist: dict[str, int] = {}
        covered_endpoints: set[str] = set()

        for suite in run.suites:
            for tc in suite.test_cases:
                test_type_dist[tc.test_type.value] = (
                    test_type_dist.get(tc.test_type.value, 0) + 1
                )
                risk_tier_dist[tc.risk_tier] = (
                    risk_tier_dist.get(tc.risk_tier, 0) + 1
                )
                covered_endpoints.add(f"{tc.method} {tc.endpoint_path}")

        coverage = CoverageMetric(
            total_endpoints=run.total_endpoints,
            covered_endpoints=len(covered_endpoints),
            coverage_pct=(
                (len(covered_endpoints) / max(run.total_endpoints, 1)) * 100
            ),
            test_type_distribution=test_type_dist,
            risk_tier_distribution=risk_tier_dist,
        )

        report = PipelineReport(
            run_id=run.run_id,
            spec_title=run.spec_title,
            timestamp=datetime.utcnow(),
            total_tests=total,
            passed=passed,
            failed=failed,
            error=errors,
            healed=healed,
            pass_rate=(passed / max(total, 1)) * 100,
            results=results,
            coverage=coverage,
            self_healing=self_healing or SelfHealingMetric(),
            token_cost=token_cost or TokenCostMetric(),
            duration_seconds=duration_seconds,
        )

        logger.info(
            "report_generated",
            run_id=run.run_id,
            total=total,
            passed=passed,
            failed=failed,
            pass_rate=report.pass_rate,
        )
        return report

    def to_json(self, report: PipelineReport, output_path: Path | None = None) -> str:
        data = report.model_dump(mode="json")
        json_str = json.dumps(data, indent=2, default=str)

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json_str)
            logger.info("report_saved_json", path=str(output_path))

        return json_str

    def to_markdown(
        self, report: PipelineReport, output_path: Path | None = None
    ) -> str:
        failed_tests = [
            r
            for r in report.results
            if r.status in (TestStatus.FAILED, TestStatus.ERROR)
        ]

        template = Template(MARKDOWN_TEMPLATE)
        md = template.render(report=report, failed_tests=failed_tests)

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(md)
            logger.info("report_saved_markdown", path=str(output_path))

        return md
